file.directory=files
spring.servlet.multipart.max-file-size=10MB

spring.datasource.url=jdbc:postgresql://localhost:5432/dreamjob
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/changelog-mater.xml
spring.liquibase.enabled=true